name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
        with:
          version: 2024.2.16 # [default: latest] mise version to install
          install: true # [default: true] run `mise install`
          cache: false # [default: true] cache mise using GitHub's cache
          experimental: true # [default: false] enable experimental features
